//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Biblio.ASP_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livres
    {
        public int id { get; set; }
        public string titre { get; set; }
        public int pages { get; set; }
        public string image { get; set; }
        public string resume { get; set; }
        public int id_auteur { get; set; }
    }
}
